version: '3'

services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile-apache
    ports:
      - "8080:80"
    networks:
      - mynetwork

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "8081:80"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
